#!/bin/bash

echo starting
exec 2>&1
set -eux
eval "export HOME=~$( id -un )"
export PATH="$HOME/bin:$PATH"

cd "$( git rev-parse --show-toplevel )"

DB=./var/live/mediainfo

if [ ! -e "$DB"/state.json ] ; then
	exec ./with-live ./bin/mediainfo-cache init --recursive "" "$DB" "$DB"
fi
exec ./with-live ./bin/mediainfo-cache update --tail "$DB" "$DB"
